//-------------------------------------------------------------------------
// WriteBack_noparam.v
//-------------------------------------------------------------------------
// This file is generated by PyMTL SystemVerilog translation pass.

// PyMTL Component WriteBack Definition
// At /home/varun/PycharmProjects/R-Type/WriteBack.py

module WriteBack_noparam
(
  input  logic [4:0] AddrDestinationRegister ,
  input  logic [0:0] clk ,
  input  logic [31:0] dataIn ,
  input  logic [0:0] isBranchInstruction ,
  input  logic [0:0] isBranchTaken ,
  input  logic [0:0] isLoadInstruction ,
  output logic [31:0] programCounterOut ,
  input  logic [0:0] reset ,
  output logic [0:0] writeEnable 
);

  // PyMTL Update Block Source
  // At /home/varun/PycharmProjects/R-Type/WriteBack.py:17
  // @update
  // def programUpdate():
  //     if s.isBranchInstruction == 1:
  //         s.programCounterOut @= s.dataIn
  
  always_comb begin : programUpdate
    if ( isBranchInstruction == 1'd1 ) begin
      programCounterOut = dataIn;
    end
  end

  // PyMTL Update Block Source
  // At /home/varun/PycharmProjects/R-Type/WriteBack.py:13
  // @update
  // def write():
  //     if s.isLoadInstruction == 1:
  //          s.writeEnable @= 1
  
  always_comb begin : write
    if ( isLoadInstruction == 1'd1 ) begin
      writeEnable = 1'd1;
    end
  end

endmodule
